//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditScore
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CIPAgeGrp", Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class CIPAgeGrp : object
    {
        
        private int AgeGrpField;
        
        private int AgeFromField;
        
        private int AgeToField;
        
        private string AgeDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AgeGrp
        {
            get
            {
                return this.AgeGrpField;
            }
            set
            {
                this.AgeGrpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AgeFrom
        {
            get
            {
                return this.AgeFromField;
            }
            set
            {
                this.AgeFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int AgeTo
        {
            get
            {
                return this.AgeToField;
            }
            set
            {
                this.AgeToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AgeDescription
        {
            get
            {
                return this.AgeDescriptionField;
            }
            set
            {
                this.AgeDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CIPScore", Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class CIPScore : object
    {
        
        private string RegnoField;
        
        private string NameField;
        
        private string ScorebandField;
        
        private double PDField;
        
        private int PointsField;
        
        private int ScorestatusidField;
        
        private string ScorestatusdescriptionField;
        
        private string ScorestatusdescriptionENField;
        
        private bool CompanyRelationField;
        
        private System.Nullable<float> RatioBelowAllField;
        
        private System.Nullable<float> RatioBelowAgeGrpField;
        
        private System.Nullable<float> RatioBelowLocationField;
        
        private int AgeGrpField;
        
        private string RegionCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Regno
        {
            get
            {
                return this.RegnoField;
            }
            set
            {
                this.RegnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Scoreband
        {
            get
            {
                return this.ScorebandField;
            }
            set
            {
                this.ScorebandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double PD
        {
            get
            {
                return this.PDField;
            }
            set
            {
                this.PDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Points
        {
            get
            {
                return this.PointsField;
            }
            set
            {
                this.PointsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Scorestatusid
        {
            get
            {
                return this.ScorestatusidField;
            }
            set
            {
                this.ScorestatusidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Scorestatusdescription
        {
            get
            {
                return this.ScorestatusdescriptionField;
            }
            set
            {
                this.ScorestatusdescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ScorestatusdescriptionEN
        {
            get
            {
                return this.ScorestatusdescriptionENField;
            }
            set
            {
                this.ScorestatusdescriptionENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool CompanyRelation
        {
            get
            {
                return this.CompanyRelationField;
            }
            set
            {
                this.CompanyRelationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<float> RatioBelowAll
        {
            get
            {
                return this.RatioBelowAllField;
            }
            set
            {
                this.RatioBelowAllField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<float> RatioBelowAgeGrp
        {
            get
            {
                return this.RatioBelowAgeGrpField;
            }
            set
            {
                this.RatioBelowAgeGrpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<float> RatioBelowLocation
        {
            get
            {
                return this.RatioBelowLocationField;
            }
            set
            {
                this.RatioBelowLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int AgeGrp
        {
            get
            {
                return this.AgeGrpField;
            }
            set
            {
                this.AgeGrpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string RegionCode
        {
            get
            {
                return this.RegionCodeField;
            }
            set
            {
                this.RegionCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CIPScorePDF", Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class CIPScorePDF : object
    {
        
        private int ScorestatusidField;
        
        private string ScorestatusdescriptionField;
        
        private string ScorestatusdescriptionENField;
        
        private bool IsPDFField;
        
        private byte[] PDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Scorestatusid
        {
            get
            {
                return this.ScorestatusidField;
            }
            set
            {
                this.ScorestatusidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Scorestatusdescription
        {
            get
            {
                return this.ScorestatusdescriptionField;
            }
            set
            {
                this.ScorestatusdescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ScorestatusdescriptionEN
        {
            get
            {
                return this.ScorestatusdescriptionENField;
            }
            set
            {
                this.ScorestatusdescriptionENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public bool IsPDF
        {
            get
            {
                return this.IsPDFField;
            }
            set
            {
                this.IsPDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] PDF
        {
            get
            {
                return this.PDFField;
            }
            set
            {
                this.PDFField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore", ConfigurationName="CreditScore.CIPIndividualScoreServiceSoap")]
    public interface CIPIndividualScoreServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.lt.is/CIPIndividualScore/AgeGrp", ReplyAction="*")]
        System.Threading.Tasks.Task<CreditScore.AgeGrpResponse> AgeGrpAsync(CreditScore.AgeGrpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.lt.is/CIPIndividualScore/Score", ReplyAction="*")]
        System.Threading.Tasks.Task<CreditScore.ScoreResponse> ScoreAsync(CreditScore.ScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.lt.is/CIPIndividualScore/ScoreEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<CreditScore.ScoreEmailResponse> ScoreEmailAsync(CreditScore.ScoreEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.lt.is/CIPIndividualScore/ScorePDF", ReplyAction="*")]
        System.Threading.Tasks.Task<CreditScore.ScorePDFResponse> ScorePDFAsync(CreditScore.ScorePDFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.lt.is/CIPIndividualScore/ScoreXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CreditScore.ScoreXMLResponse> ScoreXMLAsync(CreditScore.ScoreXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.lt.is/CIPIndividualScore/ScoreEmailXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CreditScore.ScoreEmailXMLResponse> ScoreEmailXMLAsync(CreditScore.ScoreEmailXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://ws.lt.is/CIPIndividualScore/AgeGrpXML", ReplyAction="*")]
        System.Threading.Tasks.Task<CreditScore.AgeGrpXMLResponse> AgeGrpXMLAsync(CreditScore.AgeGrpXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgeGrpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgeGrp", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.AgeGrpRequestBody Body;
        
        public AgeGrpRequest()
        {
        }
        
        public AgeGrpRequest(CreditScore.AgeGrpRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class AgeGrpRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AgeGrpRequestBody()
        {
        }
        
        public AgeGrpRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgeGrpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgeGrpResponse", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.AgeGrpResponseBody Body;
        
        public AgeGrpResponse()
        {
        }
        
        public AgeGrpResponse(CreditScore.AgeGrpResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class AgeGrpResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CreditScore.CIPAgeGrp[] AgeGrpResult;
        
        public AgeGrpResponseBody()
        {
        }
        
        public AgeGrpResponseBody(CreditScore.CIPAgeGrp[] AgeGrpResult)
        {
            this.AgeGrpResult = AgeGrpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Score", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreRequestBody Body;
        
        public ScoreRequest()
        {
        }
        
        public ScoreRequest(CreditScore.ScoreRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requesterRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subjectRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string queryInformation;
        
        public ScoreRequestBody()
        {
        }
        
        public ScoreRequestBody(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            this.username = username;
            this.password = password;
            this.requesterRegNo = requesterRegNo;
            this.subjectRegNo = subjectRegNo;
            this.queryInformation = queryInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScoreResponse", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreResponseBody Body;
        
        public ScoreResponse()
        {
        }
        
        public ScoreResponse(CreditScore.ScoreResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CreditScore.CIPScore ScoreResult;
        
        public ScoreResponseBody()
        {
        }
        
        public ScoreResponseBody(CreditScore.CIPScore ScoreResult)
        {
            this.ScoreResult = ScoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScoreEmail", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreEmailRequestBody Body;
        
        public ScoreEmailRequest()
        {
        }
        
        public ScoreEmailRequest(CreditScore.ScoreEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requesterRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subjectRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string queryInformation;
        
        public ScoreEmailRequestBody()
        {
        }
        
        public ScoreEmailRequestBody(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            this.username = username;
            this.password = password;
            this.requesterRegNo = requesterRegNo;
            this.subjectRegNo = subjectRegNo;
            this.queryInformation = queryInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScoreEmailResponse", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreEmailResponseBody Body;
        
        public ScoreEmailResponse()
        {
        }
        
        public ScoreEmailResponse(CreditScore.ScoreEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreEmailResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CreditScore.CIPScore ScoreEmailResult;
        
        public ScoreEmailResponseBody()
        {
        }
        
        public ScoreEmailResponseBody(CreditScore.CIPScore ScoreEmailResult)
        {
            this.ScoreEmailResult = ScoreEmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScorePDFRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScorePDF", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScorePDFRequestBody Body;
        
        public ScorePDFRequest()
        {
        }
        
        public ScorePDFRequest(CreditScore.ScorePDFRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScorePDFRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requesterRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subjectRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string queryInformation;
        
        public ScorePDFRequestBody()
        {
        }
        
        public ScorePDFRequestBody(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            this.username = username;
            this.password = password;
            this.requesterRegNo = requesterRegNo;
            this.subjectRegNo = subjectRegNo;
            this.queryInformation = queryInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScorePDFResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScorePDFResponse", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScorePDFResponseBody Body;
        
        public ScorePDFResponse()
        {
        }
        
        public ScorePDFResponse(CreditScore.ScorePDFResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScorePDFResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CreditScore.CIPScorePDF ScorePDFResult;
        
        public ScorePDFResponseBody()
        {
        }
        
        public ScorePDFResponseBody(CreditScore.CIPScorePDF ScorePDFResult)
        {
            this.ScorePDFResult = ScorePDFResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScoreXML", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreXMLRequestBody Body;
        
        public ScoreXMLRequest()
        {
        }
        
        public ScoreXMLRequest(CreditScore.ScoreXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requesterRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subjectRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string queryInformation;
        
        public ScoreXMLRequestBody()
        {
        }
        
        public ScoreXMLRequestBody(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            this.username = username;
            this.password = password;
            this.requesterRegNo = requesterRegNo;
            this.subjectRegNo = subjectRegNo;
            this.queryInformation = queryInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScoreXMLResponse", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreXMLResponseBody Body;
        
        public ScoreXMLResponse()
        {
        }
        
        public ScoreXMLResponse(CreditScore.ScoreXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ScoreXMLResult;
        
        public ScoreXMLResponseBody()
        {
        }
        
        public ScoreXMLResponseBody(string ScoreXMLResult)
        {
            this.ScoreXMLResult = ScoreXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreEmailXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScoreEmailXML", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreEmailXMLRequestBody Body;
        
        public ScoreEmailXMLRequest()
        {
        }
        
        public ScoreEmailXMLRequest(CreditScore.ScoreEmailXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreEmailXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requesterRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subjectRegNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string queryInformation;
        
        public ScoreEmailXMLRequestBody()
        {
        }
        
        public ScoreEmailXMLRequestBody(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            this.username = username;
            this.password = password;
            this.requesterRegNo = requesterRegNo;
            this.subjectRegNo = subjectRegNo;
            this.queryInformation = queryInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ScoreEmailXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ScoreEmailXMLResponse", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.ScoreEmailXMLResponseBody Body;
        
        public ScoreEmailXMLResponse()
        {
        }
        
        public ScoreEmailXMLResponse(CreditScore.ScoreEmailXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class ScoreEmailXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ScoreEmailXMLResult;
        
        public ScoreEmailXMLResponseBody()
        {
        }
        
        public ScoreEmailXMLResponseBody(string ScoreEmailXMLResult)
        {
            this.ScoreEmailXMLResult = ScoreEmailXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgeGrpXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgeGrpXML", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.AgeGrpXMLRequestBody Body;
        
        public AgeGrpXMLRequest()
        {
        }
        
        public AgeGrpXMLRequest(CreditScore.AgeGrpXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class AgeGrpXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AgeGrpXMLRequestBody()
        {
        }
        
        public AgeGrpXMLRequestBody(string username, string password)
        {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgeGrpXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgeGrpXMLResponse", Namespace="https://ws.lt.is/CIPIndividualScore", Order=0)]
        public CreditScore.AgeGrpXMLResponseBody Body;
        
        public AgeGrpXMLResponse()
        {
        }
        
        public AgeGrpXMLResponse(CreditScore.AgeGrpXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://ws.lt.is/CIPIndividualScore")]
    public partial class AgeGrpXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgeGrpXMLResult;
        
        public AgeGrpXMLResponseBody()
        {
        }
        
        public AgeGrpXMLResponseBody(string AgeGrpXMLResult)
        {
            this.AgeGrpXMLResult = AgeGrpXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public interface CIPIndividualScoreServiceSoapChannel : CreditScore.CIPIndividualScoreServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public partial class CIPIndividualScoreServiceSoapClient : System.ServiceModel.ClientBase<CreditScore.CIPIndividualScoreServiceSoap>, CreditScore.CIPIndividualScoreServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CIPIndividualScoreServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CIPIndividualScoreServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CIPIndividualScoreServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CIPIndividualScoreServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CIPIndividualScoreServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CIPIndividualScoreServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CIPIndividualScoreServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CIPIndividualScoreServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditScore.AgeGrpResponse> CreditScore.CIPIndividualScoreServiceSoap.AgeGrpAsync(CreditScore.AgeGrpRequest request)
        {
            return base.Channel.AgeGrpAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditScore.AgeGrpResponse> AgeGrpAsync(string username, string password)
        {
            CreditScore.AgeGrpRequest inValue = new CreditScore.AgeGrpRequest();
            inValue.Body = new CreditScore.AgeGrpRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((CreditScore.CIPIndividualScoreServiceSoap)(this)).AgeGrpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditScore.ScoreResponse> CreditScore.CIPIndividualScoreServiceSoap.ScoreAsync(CreditScore.ScoreRequest request)
        {
            return base.Channel.ScoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditScore.ScoreResponse> ScoreAsync(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            CreditScore.ScoreRequest inValue = new CreditScore.ScoreRequest();
            inValue.Body = new CreditScore.ScoreRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requesterRegNo = requesterRegNo;
            inValue.Body.subjectRegNo = subjectRegNo;
            inValue.Body.queryInformation = queryInformation;
            return ((CreditScore.CIPIndividualScoreServiceSoap)(this)).ScoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditScore.ScoreEmailResponse> CreditScore.CIPIndividualScoreServiceSoap.ScoreEmailAsync(CreditScore.ScoreEmailRequest request)
        {
            return base.Channel.ScoreEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditScore.ScoreEmailResponse> ScoreEmailAsync(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            CreditScore.ScoreEmailRequest inValue = new CreditScore.ScoreEmailRequest();
            inValue.Body = new CreditScore.ScoreEmailRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requesterRegNo = requesterRegNo;
            inValue.Body.subjectRegNo = subjectRegNo;
            inValue.Body.queryInformation = queryInformation;
            return ((CreditScore.CIPIndividualScoreServiceSoap)(this)).ScoreEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditScore.ScorePDFResponse> CreditScore.CIPIndividualScoreServiceSoap.ScorePDFAsync(CreditScore.ScorePDFRequest request)
        {
            return base.Channel.ScorePDFAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditScore.ScorePDFResponse> ScorePDFAsync(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            CreditScore.ScorePDFRequest inValue = new CreditScore.ScorePDFRequest();
            inValue.Body = new CreditScore.ScorePDFRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requesterRegNo = requesterRegNo;
            inValue.Body.subjectRegNo = subjectRegNo;
            inValue.Body.queryInformation = queryInformation;
            return ((CreditScore.CIPIndividualScoreServiceSoap)(this)).ScorePDFAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditScore.ScoreXMLResponse> CreditScore.CIPIndividualScoreServiceSoap.ScoreXMLAsync(CreditScore.ScoreXMLRequest request)
        {
            return base.Channel.ScoreXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditScore.ScoreXMLResponse> ScoreXMLAsync(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            CreditScore.ScoreXMLRequest inValue = new CreditScore.ScoreXMLRequest();
            inValue.Body = new CreditScore.ScoreXMLRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requesterRegNo = requesterRegNo;
            inValue.Body.subjectRegNo = subjectRegNo;
            inValue.Body.queryInformation = queryInformation;
            return ((CreditScore.CIPIndividualScoreServiceSoap)(this)).ScoreXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditScore.ScoreEmailXMLResponse> CreditScore.CIPIndividualScoreServiceSoap.ScoreEmailXMLAsync(CreditScore.ScoreEmailXMLRequest request)
        {
            return base.Channel.ScoreEmailXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditScore.ScoreEmailXMLResponse> ScoreEmailXMLAsync(string username, string password, string requesterRegNo, string subjectRegNo, string queryInformation)
        {
            CreditScore.ScoreEmailXMLRequest inValue = new CreditScore.ScoreEmailXMLRequest();
            inValue.Body = new CreditScore.ScoreEmailXMLRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requesterRegNo = requesterRegNo;
            inValue.Body.subjectRegNo = subjectRegNo;
            inValue.Body.queryInformation = queryInformation;
            return ((CreditScore.CIPIndividualScoreServiceSoap)(this)).ScoreEmailXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CreditScore.AgeGrpXMLResponse> CreditScore.CIPIndividualScoreServiceSoap.AgeGrpXMLAsync(CreditScore.AgeGrpXMLRequest request)
        {
            return base.Channel.AgeGrpXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<CreditScore.AgeGrpXMLResponse> AgeGrpXMLAsync(string username, string password)
        {
            CreditScore.AgeGrpXMLRequest inValue = new CreditScore.AgeGrpXMLRequest();
            inValue.Body = new CreditScore.AgeGrpXMLRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((CreditScore.CIPIndividualScoreServiceSoap)(this)).AgeGrpXMLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CIPIndividualScoreServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CIPIndividualScoreServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CIPIndividualScoreServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsdemo.lt.is/CIPIndividualScore/CIPIndividualScoreService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CIPIndividualScoreServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsdemo.lt.is/CIPIndividualScore/CIPIndividualScoreService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CIPIndividualScoreServiceSoap,
            
            CIPIndividualScoreServiceSoap12,
        }
    }
}
