//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DebtorStatus
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DssResult", Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class DssResult : object
    {
        
        private long UsageIdField;
        
        private string RequestIdField;
        
        private bool ContainsPdfDocumentField;
        
        private byte[] PdfDocumentField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UsageId
        {
            get
            {
                return this.UsageIdField;
            }
            set
            {
                this.UsageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool ContainsPdfDocument
        {
            get
            {
                return this.ContainsPdfDocumentField;
            }
            set
            {
                this.ContainsPdfDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] PdfDocument
        {
            get
            {
                return this.PdfDocumentField;
            }
            set
            {
                this.PdfDocumentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DssResultFull", Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class DssResultFull : object
    {
        
        private byte[] PDFField;
        
        private bool ContainsPdfDocumentField;
        
        private string RequestIDField;
        
        private System.DateTime DateField;
        
        private DebtorStatus.Subject SubjectField;
        
        private bool IsOnDDDField;
        
        private bool IsOnDDDNonLibraField;
        
        private long TotalMonthlyPaymentField;
        
        private long TotalLoanDebtorField;
        
        private long TotalDefaultedField;
        
        private long TotalLoanGuaranteeField;
        
        private long TotalObligationsField;
        
        private long TotalObligationsAndUnusedOverdraftField;
        
        private DebtorStatus.Loan[] LoansField;
        
        private DebtorStatus.LoanGuaranteed[] LoansGuaranteedField;
        
        private DebtorStatus.Member[] MembersField;
        
        private DebtorStatus.Member[] MembersFailedField;
        
        private DebtorStatus.Member[] MembersWithDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] PDF
        {
            get
            {
                return this.PDFField;
            }
            set
            {
                this.PDFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool ContainsPdfDocument
        {
            get
            {
                return this.ContainsPdfDocumentField;
            }
            set
            {
                this.ContainsPdfDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public DebtorStatus.Subject Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool IsOnDDD
        {
            get
            {
                return this.IsOnDDDField;
            }
            set
            {
                this.IsOnDDDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool IsOnDDDNonLibra
        {
            get
            {
                return this.IsOnDDDNonLibraField;
            }
            set
            {
                this.IsOnDDDNonLibraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long TotalMonthlyPayment
        {
            get
            {
                return this.TotalMonthlyPaymentField;
            }
            set
            {
                this.TotalMonthlyPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public long TotalLoanDebtor
        {
            get
            {
                return this.TotalLoanDebtorField;
            }
            set
            {
                this.TotalLoanDebtorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long TotalDefaulted
        {
            get
            {
                return this.TotalDefaultedField;
            }
            set
            {
                this.TotalDefaultedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public long TotalLoanGuarantee
        {
            get
            {
                return this.TotalLoanGuaranteeField;
            }
            set
            {
                this.TotalLoanGuaranteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public long TotalObligations
        {
            get
            {
                return this.TotalObligationsField;
            }
            set
            {
                this.TotalObligationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public long TotalObligationsAndUnusedOverdraft
        {
            get
            {
                return this.TotalObligationsAndUnusedOverdraftField;
            }
            set
            {
                this.TotalObligationsAndUnusedOverdraftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public DebtorStatus.Loan[] Loans
        {
            get
            {
                return this.LoansField;
            }
            set
            {
                this.LoansField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public DebtorStatus.LoanGuaranteed[] LoansGuaranteed
        {
            get
            {
                return this.LoansGuaranteedField;
            }
            set
            {
                this.LoansGuaranteedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public DebtorStatus.Member[] Members
        {
            get
            {
                return this.MembersField;
            }
            set
            {
                this.MembersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public DebtorStatus.Member[] MembersFailed
        {
            get
            {
                return this.MembersFailedField;
            }
            set
            {
                this.MembersFailedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public DebtorStatus.Member[] MembersWithData
        {
            get
            {
                return this.MembersWithDataField;
            }
            set
            {
                this.MembersWithDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class Subject : object
    {
        
        private string NationalIDField;
        
        private string NameField;
        
        private string AddressField;
        
        private string PostalCodeField;
        
        private string CityField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NationalID
        {
            get
            {
                return this.NationalIDField;
            }
            set
            {
                this.NationalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Loan", Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class Loan : object
    {
        
        private string LoanNumberField;
        
        private bool InTotalMonthlyPaymentField;
        
        private System.Nullable<long> MonthlyPaymentField;
        
        private string LoanTypeField;
        
        private string CreditorRegnoField;
        
        private string GuaranteeField;
        
        private long AuthorizedOverdraftField;
        
        private long TotalAmountField;
        
        private long DefaultedField;
        
        private long UnusedOverdraftField;
        
        private long RemainingMonthsField;
        
        private System.Nullable<System.DateTime> OldestDefaultedPaymentField;
        
        private bool InLegalProcessField;
        
        private string CreditorShortNameField;
        
        private string DebtorTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoanNumber
        {
            get
            {
                return this.LoanNumberField;
            }
            set
            {
                this.LoanNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool InTotalMonthlyPayment
        {
            get
            {
                return this.InTotalMonthlyPaymentField;
            }
            set
            {
                this.InTotalMonthlyPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<long> MonthlyPayment
        {
            get
            {
                return this.MonthlyPaymentField;
            }
            set
            {
                this.MonthlyPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LoanType
        {
            get
            {
                return this.LoanTypeField;
            }
            set
            {
                this.LoanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CreditorRegno
        {
            get
            {
                return this.CreditorRegnoField;
            }
            set
            {
                this.CreditorRegnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Guarantee
        {
            get
            {
                return this.GuaranteeField;
            }
            set
            {
                this.GuaranteeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long AuthorizedOverdraft
        {
            get
            {
                return this.AuthorizedOverdraftField;
            }
            set
            {
                this.AuthorizedOverdraftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public long Defaulted
        {
            get
            {
                return this.DefaultedField;
            }
            set
            {
                this.DefaultedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long UnusedOverdraft
        {
            get
            {
                return this.UnusedOverdraftField;
            }
            set
            {
                this.UnusedOverdraftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public long RemainingMonths
        {
            get
            {
                return this.RemainingMonthsField;
            }
            set
            {
                this.RemainingMonthsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<System.DateTime> OldestDefaultedPayment
        {
            get
            {
                return this.OldestDefaultedPaymentField;
            }
            set
            {
                this.OldestDefaultedPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool InLegalProcess
        {
            get
            {
                return this.InLegalProcessField;
            }
            set
            {
                this.InLegalProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CreditorShortName
        {
            get
            {
                return this.CreditorShortNameField;
            }
            set
            {
                this.CreditorShortNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string DebtorType
        {
            get
            {
                return this.DebtorTypeField;
            }
            set
            {
                this.DebtorTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanGuaranteed", Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class LoanGuaranteed : object
    {
        
        private string LoanNumberField;
        
        private string LoanTypeField;
        
        private string CreditorRegnoField;
        
        private string GuaranteeFormField;
        
        private long AuthorizedOverdraftField;
        
        private long TotalAmountField;
        
        private long DefaultedField;
        
        private long UnusedOverdraftField;
        
        private long RemainingMonthsField;
        
        private System.Nullable<System.DateTime> OldestDefaultedPaymentField;
        
        private bool InLegalProcessField;
        
        private string ProviderNameField;
        
        private string DebtorTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoanNumber
        {
            get
            {
                return this.LoanNumberField;
            }
            set
            {
                this.LoanNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoanType
        {
            get
            {
                return this.LoanTypeField;
            }
            set
            {
                this.LoanTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CreditorRegno
        {
            get
            {
                return this.CreditorRegnoField;
            }
            set
            {
                this.CreditorRegnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string GuaranteeForm
        {
            get
            {
                return this.GuaranteeFormField;
            }
            set
            {
                this.GuaranteeFormField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long AuthorizedOverdraft
        {
            get
            {
                return this.AuthorizedOverdraftField;
            }
            set
            {
                this.AuthorizedOverdraftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long TotalAmount
        {
            get
            {
                return this.TotalAmountField;
            }
            set
            {
                this.TotalAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public long Defaulted
        {
            get
            {
                return this.DefaultedField;
            }
            set
            {
                this.DefaultedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long UnusedOverdraft
        {
            get
            {
                return this.UnusedOverdraftField;
            }
            set
            {
                this.UnusedOverdraftField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public long RemainingMonths
        {
            get
            {
                return this.RemainingMonthsField;
            }
            set
            {
                this.RemainingMonthsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> OldestDefaultedPayment
        {
            get
            {
                return this.OldestDefaultedPaymentField;
            }
            set
            {
                this.OldestDefaultedPaymentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool InLegalProcess
        {
            get
            {
                return this.InLegalProcessField;
            }
            set
            {
                this.InLegalProcessField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DebtorType
        {
            get
            {
                return this.DebtorTypeField;
            }
            set
            {
                this.DebtorTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class Member : object
    {
        
        private string NameField;
        
        private string RegnoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Regno
        {
            get
            {
                return this.RegnoField;
            }
            set
            {
                this.RegnoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.lt.is/DebtorStatus", ConfigurationName="DebtorStatus.ServiceSoap")]
    public interface ServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.lt.is/DebtorStatus/GetDebtorStatusPdf", ReplyAction="*")]
        System.Threading.Tasks.Task<DebtorStatus.GetDebtorStatusPdfResponse> GetDebtorStatusPdfAsync(DebtorStatus.GetDebtorStatusPdfRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.lt.is/DebtorStatus/GetDebtorStatusFull", ReplyAction="*")]
        System.Threading.Tasks.Task<DebtorStatus.GetDebtorStatusFullResponse> GetDebtorStatusFullAsync(DebtorStatus.GetDebtorStatusFullRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDebtorStatusPdfRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDebtorStatusPdf", Namespace="http://ws.lt.is/DebtorStatus", Order=0)]
        public DebtorStatus.GetDebtorStatusPdfRequestBody Body;
        
        public GetDebtorStatusPdfRequest()
        {
        }
        
        public GetDebtorStatusPdfRequest(DebtorStatus.GetDebtorStatusPdfRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class GetDebtorStatusPdfRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requesterNationalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subjectNationalId;
        
        public GetDebtorStatusPdfRequestBody()
        {
        }
        
        public GetDebtorStatusPdfRequestBody(string username, string password, string requesterNationalId, string subjectNationalId)
        {
            this.username = username;
            this.password = password;
            this.requesterNationalId = requesterNationalId;
            this.subjectNationalId = subjectNationalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDebtorStatusPdfResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDebtorStatusPdfResponse", Namespace="http://ws.lt.is/DebtorStatus", Order=0)]
        public DebtorStatus.GetDebtorStatusPdfResponseBody Body;
        
        public GetDebtorStatusPdfResponse()
        {
        }
        
        public GetDebtorStatusPdfResponse(DebtorStatus.GetDebtorStatusPdfResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class GetDebtorStatusPdfResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebtorStatus.DssResult GetDebtorStatusPdfResult;
        
        public GetDebtorStatusPdfResponseBody()
        {
        }
        
        public GetDebtorStatusPdfResponseBody(DebtorStatus.DssResult GetDebtorStatusPdfResult)
        {
            this.GetDebtorStatusPdfResult = GetDebtorStatusPdfResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDebtorStatusFullRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDebtorStatusFull", Namespace="http://ws.lt.is/DebtorStatus", Order=0)]
        public DebtorStatus.GetDebtorStatusFullRequestBody Body;
        
        public GetDebtorStatusFullRequest()
        {
        }
        
        public GetDebtorStatusFullRequest(DebtorStatus.GetDebtorStatusFullRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class GetDebtorStatusFullRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requesterNationalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string subjectNationalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool makePDF;
        
        public GetDebtorStatusFullRequestBody()
        {
        }
        
        public GetDebtorStatusFullRequestBody(string username, string password, string requesterNationalId, string subjectNationalId, bool makePDF)
        {
            this.username = username;
            this.password = password;
            this.requesterNationalId = requesterNationalId;
            this.subjectNationalId = subjectNationalId;
            this.makePDF = makePDF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDebtorStatusFullResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDebtorStatusFullResponse", Namespace="http://ws.lt.is/DebtorStatus", Order=0)]
        public DebtorStatus.GetDebtorStatusFullResponseBody Body;
        
        public GetDebtorStatusFullResponse()
        {
        }
        
        public GetDebtorStatusFullResponse(DebtorStatus.GetDebtorStatusFullResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ws.lt.is/DebtorStatus")]
    public partial class GetDebtorStatusFullResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DebtorStatus.DssResultFull GetDebtorStatusFullResult;
        
        public GetDebtorStatusFullResponseBody()
        {
        }
        
        public GetDebtorStatusFullResponseBody(DebtorStatus.DssResultFull GetDebtorStatusFullResult)
        {
            this.GetDebtorStatusFullResult = GetDebtorStatusFullResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public interface ServiceSoapChannel : DebtorStatus.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.3.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<DebtorStatus.ServiceSoap>, DebtorStatus.ServiceSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebtorStatus.GetDebtorStatusPdfResponse> DebtorStatus.ServiceSoap.GetDebtorStatusPdfAsync(DebtorStatus.GetDebtorStatusPdfRequest request)
        {
            return base.Channel.GetDebtorStatusPdfAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebtorStatus.GetDebtorStatusPdfResponse> GetDebtorStatusPdfAsync(string username, string password, string requesterNationalId, string subjectNationalId)
        {
            DebtorStatus.GetDebtorStatusPdfRequest inValue = new DebtorStatus.GetDebtorStatusPdfRequest();
            inValue.Body = new DebtorStatus.GetDebtorStatusPdfRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requesterNationalId = requesterNationalId;
            inValue.Body.subjectNationalId = subjectNationalId;
            return ((DebtorStatus.ServiceSoap)(this)).GetDebtorStatusPdfAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DebtorStatus.GetDebtorStatusFullResponse> DebtorStatus.ServiceSoap.GetDebtorStatusFullAsync(DebtorStatus.GetDebtorStatusFullRequest request)
        {
            return base.Channel.GetDebtorStatusFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<DebtorStatus.GetDebtorStatusFullResponse> GetDebtorStatusFullAsync(string username, string password, string requesterNationalId, string subjectNationalId, bool makePDF)
        {
            DebtorStatus.GetDebtorStatusFullRequest inValue = new DebtorStatus.GetDebtorStatusFullRequest();
            inValue.Body = new DebtorStatus.GetDebtorStatusFullRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.requesterNationalId = requesterNationalId;
            inValue.Body.subjectNationalId = subjectNationalId;
            inValue.Body.makePDF = makePDF;
            return ((DebtorStatus.ServiceSoap)(this)).GetDebtorStatusFullAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ds.lt.is/DebtorStatus/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ds.lt.is/DebtorStatus/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
